name: 1. Build & Deploy Apollo Federated Gateway
run-name: Build & Deploy Apollo Federated Gateway

on:
  push:
    paths-ignore:
      - '.github/**'
  repository_dispatch:
    types: [update_subgraph]
  workflow_dispatch:

jobs:
  build_and_deploy:
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-federated-gateway.yaml@main
    secrets:
      SUBGRAPH_PULL_TOKEN: ${{'{'}}{ secrets.SUBGRAPH_PULL_TOKEN }}
      REPOSITORY_PUSH_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
