on:
  workflow_dispatch:

permissions: write-all

name: 2. Tag & Release
run-name: Tag & Release by @${{'{'}}{ github.triggering_actor }}

jobs:
  tag_version:
    name: Tag Version
    uses: p6m-dev/github-actions/.github/workflows/cut-tag-docker.yml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

